Save build artifacts for all configurations
MFlowCode/MFC pull request #204
Opened 2023-08-12 02:19 UTC by henryleberre

Closes #203.

2023-08-12 16:02 UTC, sbryngelson requested changes

2023-08-12 16:02 UTC, sbryngelson commented on toolchain/mfc/build.py
comment goes here

2023-08-12 16:02 UTC, sbryngelson commented on toolchain/mfc/build.py
> +
comment goes here

2023-08-12 16:02 UTC, sbryngelson commented on toolchain/mfc/build.py
>  def is_target_configured(target: MFCTarget) -> bool:
comment goes here

2023-08-12 16:02 UTC, sbryngelson commented on toolchain/mfc/run/engines.py
>      def get_binpath(self, target: str) -> str:
comment goes here

2023-08-12 16:02 UTC, sbryngelson commented on toolchain/mfc/run/engines.py
>  def _interactive_working_worker(cmd, q):
comment goes here

2023-08-12 16:02 UTC, sbryngelson commented on toolchain/mfc/state.py
comment goes here

2023-08-12 16:02 UTC, sbryngelson commented on toolchain/mfc/state.py
> +
comment goes here

2023-08-12 16:02 UTC, sbryngelson commented on toolchain/mfc/state.py
> +
comment goes here

2023-08-12 16:02 UTC, sbryngelson commented on toolchain/mfc/build.py
comment goes here (what do the arguments mean?)

2023-08-13 17:01 UTC, sbryngelson commented
alternative to adding a bunch of comments is to rewrite all of the one-liners into more expressive multi-line logic.

2023-08-26 22:27 UTC, sbryngelson commented
This passes on GPU now. Do we need new goldenfiles for `weno_avg`? Presumably, they were originally generated via CPU by @haochey , so changing GPU behavior shouldn't change the 'correct answer' or goldenfile.

2023-08-26 22:34 UTC, haochey commented
> This passes on GPU now. Do we need new goldenfiles for `weno_avg`? Presumably, they were originally generated via CPU by @haochey , so changing GPU behavior shouldn't change the 'correct answer' or goldenfile.

Hi @sbryngelson , Yes, the golden files with weno_avg were originally genearted via CPU with GNU and test on GPU on Phoenix passes too.

2023-08-26 22:47 UTC, sbryngelson commented
@haochey they started failing (see here https://github.com/MFlowCode/MFC/actions/runs/5969092038/job/16194270272?pr=204) once @henryleberre fixed part of the test suite. Then @henryleberre fixed the GPU code (see here https://github.com/MFlowCode/MFC/pull/204/commits/ec688966757a5fdd882a794b46aef348878a4c18). Thank you @henryleberre !

2023-08-26 22:53 UTC, haochey commented
> @haochey they started failing (see here https://github.com/MFlowCode/MFC/actions/runs/5969092038/job/16194270272?pr=204) once @henryleberre fixed part of the test suite. Then @henryleberre fixed the GPU code (see here [ec68896](https://github.com/MFlowCode/MFC/commit/ec688966757a5fdd882a794b46aef348878a4c18)). Thank you @henryleberre !

Thanks! @henryleberre

2023-08-27 02:26 UTC, merged