File Per Process IO, performance summary in docs, new example case.
MFlowCode/MFC pull request #256
Opened 2023-12-13 18:43 UTC by wilfonba

This PR adds the option to use file per process IO when running on very large numbers of GPUs where it was found that shared file IO wasn't very performant.

It also adds a performance summary page to the documentation that was suggested in the MFC Slack.

It also adds improved error messaging for namelist read fails in m_start_up in all three modules.

Lastly, it adds the Riemann test problem requested in #174 .

2023-12-13 19:23 UTC, sbryngelson requested changes

2023-12-13 19:23 UTC, sbryngelson commented on docs/res/strongScaling/S01.95
what is this file?

2023-12-13 19:23 UTC, sbryngelson commented on docs/documentation/expectedPerformance.md
> +| Nvidia V100          | 1       | 113.4k         | 26.2k          | N/A          | NVHPC 22.11 | PACE Phoenix  |
Do we get different performance on Summit V100? they are smx2 with 16GB (Summit) vs pcie with 16 or 32gb (Phoenix).

2023-12-13 19:23 UTC, sbryngelson commented on docs/documentation/expectedPerformance.md
> +| Intel Xeon Gold 6226 | 12      | 5.4k           | 1.6k           | 0.8k         | GNU 10.3.0  | Pace Phoenix  |
Pace -> PACE.

2023-12-13 19:23 UTC, sbryngelson commented on src/post_process/m_global_parameters.fpp
> +        file_per_process = .true.
i thought we discussed making this false by default since it seems that only 8000 GPUs on Frontier gives an advantage for this I/O?

2023-12-13 19:24 UTC, sbryngelson commented on docs/documentation/expectedPerformance.md
> +MFC weask scales to 65,536 AMD MI250X GPUs on OLCF Frontier with 96% efficiency.
comment on what % this is of the whole computer

2023-12-13 19:24 UTC, sbryngelson commented on docs/documentation/expectedPerformance.md
> +MFC weak scales to 13,824 V100 Nvidia V100 GPUs on OLCF Summit with 97% efficiency.
comment on what % this is of whole computer

2023-12-13 19:25 UTC, sbryngelson commented on docs/documentation/expectedPerformance.md
> +MFC Weak scales to 13,824 Power9 CPU cores on OLCF Summit with 1% of ideal scaling.
1%?

2023-12-13 19:27 UTC, sbryngelson commented
can you also fix #255

2023-12-14 15:09 UTC, wilfonba commented on docs/res/strongScaling/S01.95
That's a good question. Probably junk.

2023-12-14 15:13 UTC, wilfonba commented on src/post_process/m_global_parameters.fpp
> +        file_per_process = .true.
Whoops...

2023-12-14 15:14 UTC, wilfonba commented on docs/documentation/expectedPerformance.md
> +MFC Weak scales to 13,824 Power9 CPU cores on OLCF Summit with 1% of ideal scaling.
To within, whoops

2023-12-14 15:59 UTC, wilfonba commented on docs/documentation/expectedPerformance.md
> +| Nvidia V100          | 1       | 113.4k         | 26.2k          | N/A          | NVHPC 22.11 | PACE Phoenix  |
Added

2023-12-14 16:01 UTC, wilfonba commented
The requested changes are done. I'm having trouble getting the documentation to build locally so I can see if it actually updates on the website, but I'm working on it.

2023-12-14 17:11 UTC, wilfonba commented
@sbryngelson This should be able to merge unless you really want this PR to take care of #255. I was talking to Henry about it, and he said, and I quote, "This is a me-problem, not a you-problem"

2023-12-14 17:31 UTC, sbryngelson commented
> @sbryngelson This should be able to merge unless you really want this PR to take care of #255. I was talking to Henry about it, and he said, and I quote, "This is a me-problem, not a you-problem"

Lol. Fine with me.

2023-12-14 17:38 UTC, sbryngelson approved these changes

2023-12-14 23:13 UTC, henryleberre approved these changes

2023-12-14 23:14 UTC, merged