GH-200 Unified Memory Support
MFlowCode/MFC pull request #470
Opened 2024-06-13 15:54 UTC by AiredaleDev

## Description

Adds a new flag to the toolchain, `--unified` which passes `-gpu=unified` to NVIDIA compilers.

Fixes #412 

### Type of change

- New feature (non-breaking change which adds functionality)

### Scope

- [ ] This PR comprises a set of related changes with a common goal

If you cannot check the above box, please split your PR into multiple PRs that each have a common goal.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce. 
Please also list any relevant details for your test configuration

- Ran 3D performance test example with and without unified memory. Tried the same case with 96M grid points, using more than 80GB of RAM and observed an OOM crash w/o unified memory and a functioning, slower run with unified memory.
- Tested w/o MPI, because I wanted to isolate effects of unified memory and because I couldn't run with MPI. The MPI build on RG for the GH-200 complains about being built w/o PMI-X, refusing to run.

**Test Configuration**:

* What computers and compilers did you use to test this:
  * Rogue's Gallery -- UWing (GH-200, aarch64)

## Checklist

- [ ] I have added comments for the new code
- [ ] I have made corresponding changes to the documentation (`docs/`)
- [ ] I ran `./mfc.sh format` before committing my code
- [ ] New and existing tests pass locally with my changes, including with GPU capability enabled (both NVIDIA hardware with NVHPC compilers and AMD hardware with CRAY compilers) and disabled
- [ ] This PR does not introduce any repeated code (it follows the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle)
- [ ] I cannot think of a way to condense this code and reduce any introduced additional line count

2024-06-13 16:16 UTC, sbryngelson approved these changes

2024-06-13 16:20 UTC, sbryngelson commented
Please add performance results to the PR

2024-06-13 16:20 UTC, sbryngelson commented
Please clarify what this means
> Tested w/o MPI, because I wanted to isolate effects of unified memory and because I couldn't run with MPI. The MPI build on RG for the Grace Hopper chip complains about being built w/o PMI-X, refusing to run.

2024-06-13 16:56 UTC, AiredaleDev commented
> Please clarify what this means
> 
> > Tested w/o MPI, because I wanted to isolate effects of unified memory and because I couldn't run with MPI. The MPI build on RG for the Grace Hopper chip complains about being built w/o PMI-X, refusing to run.
> 
> Does regular MFC run without `--unified` on that node? I believe it does

I was originally going to write this:

> It runs fine with or without `--unified` -- it's just MPI that acts strange. I built and tested with `--no-mpi`. When I build with `--mpi`, independent of `--unified`, I get this message:
> 
> ```+ srun --ntasks 1 /nethome/choechst3/MFC/build/install/521638aec8/bin/syscheck                                                                                                                
> [rg-uwing-1:552224] OPAL ERROR: Unreachable in file ext3x_client.c at line 112                                                                                                                
>  [TEST] MPI: call mpi_init(ierr)                                                                                                                                                              
> --------------------------------------------------------------------------                                                                                                                    
> The application appears to have been direct launched using "srun",                                                                                                                            
> but OMPI was not built with SLURM's PMI support and therefore cannot                                                                                                                          
> execute. There are several options for building PMI support under                                                                                                                             
> SLURM, depending upon the SLURM version you are using:                                                                                                                                        
>                                                                                                                                                                                               
>   version 16.05 or later: you can use SLURM's PMIx support. This                                                                                                                              
>   requires that you configure and build SLURM --with-pmix.                                                                                                                                    
>                                                                                                                                                                                               
>   Versions earlier than 16.05: you must use either SLURM's PMI-1 or                                                                                                                           
>   PMI-2 support. SLURM builds PMI-1 by default, or you can manually                                                                                                                           
>   install PMI-2. You must then build Open MPI using --with-pmi pointing                                                                                                                       
>   to the SLURM PMI library location.                                                                                                                                                          
>                                                                                                                                                                                               
> Please configure as appropriate and try again.                                                                                                                                                
> --------------------------------------------------------------------------                                                                                                                    
> *** An error occurred in MPI_Init                                           
> ```
> I believe this is just a quirk of Rogue's Gallery.

but I just tried using `mpirun` instead, in which it works just fine!

2024-06-13 17:06 UTC, AiredaleDev commented
> Please add performance results to the PR

Added!

2024-06-13 20:42 UTC, henryleberre requested changes

2024-06-13 20:42 UTC, henryleberre commented on CMakeLists.txt
> +	    # GH-200 Unified Memory Suppory
`Suppory` -> `Support`

2024-06-13 20:42 UTC, henryleberre commented on CMakeLists.txt
> +	    target_compile_options(${ARGS_TARGET}
Add back the indentation

2024-06-13 20:42 UTC, henryleberre commented on CMakeLists.txt
> +            endif()
Indentation!

2024-06-13 20:42 UTC, henryleberre commented on toolchain/main.py
> +        a = a if a is not None else ''
nit that applies to the code that was there before: I think we can actually write `a or ''`.

2024-06-14 10:51 UTC, henryleberre approved these changes
🚀

2024-06-14 12:13 UTC, merged