Print all test case error messages together at the end
MFlowCode/MFC pull request #745
Opened 2024-11-24 02:35 UTC by wilfonba

## Description

I have recently found the behavior described in #744 to be annoying. This PR addresses that by keeping a list of all failed tests and printing the errors all together at the end.

Fixes #744

### Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

### Scope

- [ ] This PR comprises a set of related changes with a common goal

## How Has This Been Tested?

Test 1: I intentionally caused tests to fail due to tolerance by commenting out `dvd(0)` in the fifth order WENO reconstruction so the solution would be wrong. The resulting output of `./mfc.sh test -j 1 -o bc=-1 > test1.txt` (without coloring) is
[test1.txt](https://github.com/user-attachments/files/17891517/test1.txt)

Test 2: Intentionally caused tests to fail due to NaNs by commenting out `beta(0)` in the fifth-order WENO reconstruction. The resulting output of `./mfc.sh test -j 1 -o bc=-1 > test2.txt` (without color) is 
[test2.txt](https://github.com/user-attachments/files/17891516/test2.txt)

2024-11-24 15:32 UTC, sbryngelson commented on test4.txt
remove this file (obviously)

2024-11-24 15:37 UTC, sbryngelson requested changes
@henryleberre might comment on the 'cleanness' of the toolchain implementation. For me, it seems reasonable and gets the job done.

2024-11-26 21:43 UTC, sbryngelson commented
Is this in conflict with something added by @henryleberre in https://github.com/MFlowCode/MFC/pull/737 ?

2024-11-26 23:44 UTC, wilfonba commented
Merged without issue

2024-11-27 01:25 UTC, sbryngelson commented
@wilfonba https://github.com/MFlowCode/MFC/pull/737 is still open (not merged)

2024-11-30 08:09 UTC, sbryngelson approved these changes

2024-11-30 08:09 UTC, merged